import { useEffect, useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { ShieldIcon, ClockIcon, UserIcon } from './Icons.jsx'

export default function Navbar({ role }) {
  const navigate=useNavigate(), location=useLocation(); const userId=localStorage.getItem('aegis_uid')||''
  const isDemoSession = role!=='admin' && localStorage.getItem('aegis_demo_mode')==='1'
  const [now,setNow]=useState(new Date()); useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[])
  const tabs=role==='admin'?[{label:'Portfolio',path:'/admin'},{label:'At-Risk',path:'/admin#risk'}]:[{label:'Dashboard',path:'/customer'},{label:'Cashflow',path:'/customer/projection'},{label:'Repayment',path:'/customer/repayment'},{label:'Anomalies',path:'/customer/anomalies'},{label:'Safety buffer',path:'/customer/buffer'}]
  const logout=()=>{localStorage.clear();navigate('/')}
  return <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-xl border-b border-slate-200"><div className="max-w-7xl mx-auto px-4 h-[68px] flex items-center justify-between gap-4"><div className="flex items-center gap-2.5 cursor-pointer" onClick={()=>navigate(role==='admin'?'/admin':'/customer')}><span className="icon-tile !w-9 !h-9"><ShieldIcon className="w-5 h-5" /></span><span className="font-bold text-lg text-slate-900">Aegis</span><span className="hidden sm:inline text-[10px] font-bold uppercase tracking-wider text-violet-700 bg-violet-50 border border-violet-100 rounded-full px-2 py-1">{role==='admin'?'Bank team':'Customer'}</span>{isDemoSession&&<span className="text-[10px] font-bold uppercase tracking-wider text-amber-700 bg-amber-50 border border-amber-200 rounded-full px-2 py-1">Demo mode</span>}</div><nav className="hidden lg:flex items-center gap-1">{tabs.map(t=><button key={t.path} onClick={()=>navigate(t.path)} className={`px-3 py-2 rounded-lg text-sm font-medium ${location.pathname===t.path?'bg-violet-50 text-violet-800':'text-slate-500 hover:text-violet-700 hover:bg-slate-50'}`}>{t.label}</button>)}</nav><div className="flex items-center gap-3"><span className="hidden md:flex items-center gap-1.5 text-xs text-slate-500"><ClockIcon className="w-3.5 h-3.5 text-violet-500" />{now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span>{userId&&<span className="hidden sm:flex items-center gap-1 text-xs text-slate-500"><UserIcon className="w-3.5 h-3.5" />{userId}</span>}<button onClick={logout} className="btn-ghost text-xs py-2">Sign out</button></div></div></header>
}
