import { useLocation, useNavigate } from 'react-router-dom'
import { ShieldIcon, ChartIcon, AlertIcon, HeartIcon, BankIcon, UserIcon, CalendarIcon } from './Icons.jsx'

export default function Sidebar({ role }) {
  const navigate = useNavigate(); const location = useLocation(); const uid = localStorage.getItem('aegis_uid') || 'Admin workspace'
  const items = role === 'admin' ? [{label:'Portfolio overview',path:'/admin',icon:<ChartIcon className="w-4 h-4"/>},{label:'At-risk users',path:'/admin#risk',icon:<AlertIcon className="w-4 h-4"/>}] : [{label:'Dashboard',path:'/customer',icon:<ChartIcon className="w-4 h-4"/>},{label:'Cashflow',path:'/customer/projection',icon:<BankIcon className="w-4 h-4"/>},{label:'Repayment',path:'/customer/repayment',icon:<HeartIcon className="w-4 h-4"/>},{label:'Anomalies',path:'/customer/anomalies',icon:<AlertIcon className="w-4 h-4"/>},{label:'Safety buffer',path:'/customer/buffer',icon:<ShieldIcon className="w-4 h-4"/>}]
  const today = new Date()
  return <aside className="hidden lg:flex fixed left-0 top-[68px] bottom-0 w-[232px] bg-white border-r border-slate-200 flex-col p-4 z-40"><div className="rounded-2xl bg-violet-50 border border-violet-100 p-4 mb-5"><div className="flex items-center gap-2 text-violet-800"><CalendarIcon className="w-4 h-4"/><span className="text-xs font-semibold">Today</span></div><p className="text-sm font-bold text-slate-900 mt-2">{today.toLocaleDateString('en-IN',{weekday:'long'})}</p><p className="text-xs text-slate-500 mt-0.5">{today.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</p></div><p className="px-3 text-[10px] uppercase tracking-[.16em] font-bold text-slate-400 mb-2">{role==='admin'?'Workspace':'Your space'}</p><nav className="space-y-1">{items.map(item=><button key={item.path} onClick={()=>navigate(item.path)} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm text-left transition-colors ${location.pathname===item.path?'bg-violet-50 text-violet-800 font-semibold':'text-slate-500 hover:bg-slate-50 hover:text-violet-700'}`}>{item.icon}<span>{item.label}</span></button>)}</nav><div className="mt-auto rounded-2xl border border-slate-100 bg-slate-50 p-3 flex items-center gap-2"><span className="icon-tile !w-8 !h-8"><UserIcon className="w-4 h-4"/></span><div className="min-w-0"><p className="text-xs font-semibold text-slate-800 truncate">{role==='admin'?'Bank team':'Signed in'}</p><p className="text-[10px] text-slate-400 truncate">{uid}</p></div></div></aside>
}
